### ISSUE TITLE
Incorrect date

### ISSUE THREAD

**Issue by AcrobaticMongoose** [sohnemann/New-Zealand-Public-Holidays#3]
Anzac Day (Mondayised) in 2032 is incorrectly listed as January 26 for the 'New Zealand Holidays - All' calendar.

Can you please re-check all other dates?

**Comment by thom-vend** [comment]
> Anzac Day (Mondayised) in 2032 is incorrectly listed as January 26 for the 'New Zealand Holidays - All' calendar.

What would be the correct day?

**Comment by AcrobaticMongoose** [comment]
> > Anzac Day (Mondayised) in 2032 is incorrectly listed as January 26 for the 'New Zealand Holidays - All' calendar.
> 
> What would be the correct day?

April 26.

**Comment by thom-vend** [comment]
Thanks @AcrobaticMongoose I've open a PR to fix and updated our fork (https://github.com/vend/New-Zealand-Public-Holidays) Will see if @sohnemann accept this contribution 😊 
Have a nice day

**Comment by sohnemann** [comment]
Thanks @AcrobaticMongoose  & @thom-vend, I have merged the changes. 😊
