### ISSUE TITLE
Create iCal for Auckland region?

### ISSUE THREAD

**Issue by chaoscreater** [sohnemann/New-Zealand-Public-Holidays#4]
Hi,

Bit of a weird request, but could you please create a new iCal link that includes "New Zealand Holidays - National" + Auckland region holidays, such as Auckland Anniversary Day? I don't need the holidays for the other regions.

**Comment by sohnemann** [comment]
Sorry, but I don't have time to do that.
If you would like to create this yourself you are more than welcome to create a Pull Request. 😃
